### ISSUE TITLE
Missing api for Delete Box

### ISSUE THREAD

**Issue by mnowakowska** [peterruggero/postmaster-nodejs#1]
On Postmaster it's option for delete box. 
https://www.postmaster.io/docs/api#deletebox
In this library missing this.

Please, cay you add this.

**Comment by CountZachula** [comment]
Our apologies, czeko! We'll get this change implemented as soon as possible. Thanks for catching it!

Z

**Comment by CountZachula** [comment]
czeko,

This issue has been resolved. The latest source and package are now publicly available.

Thanks,
Z
