### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by ghost** [peterruggero/postmaster-nodejs#4]
Started on the wrong repository (postmaster/postmaster-api#27), problem in fact comes from the nodejs SDK documentation. It wasn't clear that I needed to instantiate like this:

``` javascript
var postmaster = require('../index')({
    apiKey: '0b9a54438fba2dc0d39be8f7c6c71a58',
    password: undefined // I was omitting this attribute
}, true); // what does the `true` stands for?
```

For password-less accounts (signed up using Facebook). I digged a little and found all my answers, but that would be great to make a better README, for _developers-friendliness_.

**Comment by CountZachula** [comment]
@kytwb,

I apologize for any confusion.

Unless you're running from source, you should instantiate per the documentation at https://www.postmaster.io/docs/api after installing postmaster-nodes through `npm`. The snippet of code you posted is from the library's test class.

That said, you are correct in that I need to outline some specific authentication cases in the README, especially for those who need to modify the solution.

Per your question in the snippet, if you follow the method call into `../index` in the root directory, I have method documentation there. The `true` parameter indicates debug mode, which prints additional information in the console.

Let me know if you have any further questions. I'll update the README at some point today.

Thanks!
Z

**Comment by ghost** [comment]
All good man.

**Comment by ghost** [comment]
Actually I'll let you close the issue when you pushed the new README.
